### ISSUE TITLE
Could you build logic from Groovy to Kotlin?

### ISSUE THREAD

**Issue by keer2345** [lWoHvYe/unicorn#296]
I want to convert `build.gradle` to `build.gradle.kts`.

**Comment by lWoHvYe** [comment]
Hi @keer2345, Thanks for advice. The concern is that if I change the build logic to Kotlin DSL, It will stick me for few months before this project works for newly released JDK.
Gradle uses Kotlin to run buildscripts written in the Kotlin DSL. It is necessary for Kotlin to have support for this in order to claim that Gradle can be run on Java 21. https://github.com/gradle/gradle/issues/25574#issuecomment-1732842944
see https://github.com/gradle/gradle/issues/25574

**Comment by lWoHvYe** [comment]
That's why [this project](https://github.com/lWoHvYe/unicorn-swarm) is still on Java 17
